-- DROP DATABASE IF EXISTS HRR43_FEC;
CREATE DATABASE IF NOT EXISTS HRR43_FEC;
USE HRR43_FEC;


DROP TABLE IF EXISTS HRR43_FEC.about;

CREATE TABLE `about` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,

  `average` float(2, 1) NOT NULL,
  `location` float(2, 1) NOT NULL,
  `cleanliness` float(2, 1) NOT NULL,
  `service` float(2, 1) NOT NULL,
  `value` float(2, 1) NOT NULL,

  `certOfExcellence` tinyint NOT NULL,
  `greenLeaders` tinyint NOT NULL,

  `aboutCopy` text NOT NULL,

  `image0` varchar(128) NOT NULL,
  `image1` varchar(128) NOT NULL,
  `image2` varchar(128) NOT NULL,
  `image3` varchar(128) NOT NULL,
  `image4` varchar(128) NOT NULL,
  `image5` varchar(128) NOT NULL,
  `image6` varchar(128) NOT NULL,

  `amenityIcon0` tinyint NOT NULL,
  `amenityCopy0` varchar(50) NOT NULL,
  `amenityIcon1` tinyint NOT NULL,
  `amenityCopy1` varchar(50) NOT NULL,
  `amenityIcon2` tinyint NOT NULL,
  `amenityCopy2` varchar(50) NOT NULL,
  `amenityIcon3` tinyint NOT NULL,
  `amenityCopy3` varchar(50) NOT NULL,
  `amenityIcon4` tinyint NOT NULL,
  `amenityCopy4` varchar(50) NOT NULL,
  `amenityIcon5` tinyint NOT NULL,
  `amenityCopy5` varchar(50) NOT NULL,
  `amenityIcon6` tinyint NOT NULL,
  `amenityCopy6` varchar(50) NOT NULL,
  `amenityIcon7` tinyint NOT NULL,
  `amenityCopy7` varchar(50) NOT NULL,

  `amenityIcon8` tinyint NOT NULL,
  `amenityCopy8` varchar(50) NOT NULL,
  `amenityIcon9` tinyint NOT NULL,
  `amenityCopy9` varchar(50) NOT NULL,
  `amenityIcon10` tinyint NOT NULL,
  `amenityCopy10` varchar(50) NOT NULL,
  `amenityIcon11` tinyint NOT NULL,
  `amenityCopy11` varchar(50) NOT NULL,
  `amenityIcon12` tinyint NOT NULL,
  `amenityCopy12` varchar(50) NOT NULL,
  `amenityIcon13` tinyint NOT NULL,
  `amenityCopy13` varchar(50) NOT NULL,
  `amenityIcon14` tinyint NOT NULL,
  `amenityCopy14` varchar(50) NOT NULL,
  `amenityIcon15` tinyint NOT NULL,
  `amenityCopy15` varchar(50) NOT NULL,

  `amenityIcon16` tinyint NOT NULL,
  `amenityCopy16` varchar(50) NOT NULL,
  `amenityIcon17` tinyint NOT NULL,
  `amenityCopy17` varchar(50) NOT NULL,
  `amenityIcon18` tinyint NOT NULL,
  `amenityCopy18` varchar(50) NOT NULL,
  `amenityIcon19` tinyint NOT NULL,
  `amenityCopy19` varchar(50) NOT NULL,
  `amenityIcon20` tinyint NOT NULL,
  `amenityCopy20` varchar(50) NOT NULL,
  `amenityIcon21` tinyint NOT NULL,
  `amenityCopy21` varchar(50) NOT NULL,
  `amenityIcon22` tinyint NOT NULL,
  `amenityCopy22` varchar(50) NOT NULL,
  `amenityIcon23` tinyint NOT NULL,
  `amenityCopy23` varchar(50) NOT NULL,

  `amenityIcon24` tinyint NOT NULL,
  `amenityCopy24` varchar(50) NOT NULL,
  `amenityIcon25` tinyint NOT NULL,
  `amenityCopy25` varchar(50) NOT NULL,
  `amenityIcon26` tinyint NOT NULL,
  `amenityCopy26` varchar(50) NOT NULL,
  `amenityIcon27` tinyint NOT NULL,
  `amenityCopy27` varchar(50) NOT NULL,
  `amenityIcon28` tinyint NOT NULL,
  `amenityCopy28` varchar(50) NOT NULL,
  `amenityIcon29` tinyint NOT NULL,
  `amenityCopy29` varchar(50) NOT NULL,
  `amenityIcon30` tinyint NOT NULL,
  `amenityCopy30` varchar(50) NOT NULL,
  `amenityIcon31` tinyint NOT NULL,
  `amenityCopy31` varchar(50) NOT NULL,

  `roomFeatureIcon0` tinyint NOT NULL,
  `roomFeatureCopy0` varchar(50) NOT NULL,
  `roomFeatureIcon1` tinyint NOT NULL,
  `roomFeatureCopy1` varchar(50) NOT NULL,
  `roomFeatureIcon2` tinyint NOT NULL,
  `roomFeatureCopy2` varchar(50) NOT NULL,
  `roomFeatureIcon3` tinyint NOT NULL,
  `roomFeatureCopy3` varchar(50) NOT NULL,
  `roomFeatureIcon4` tinyint NOT NULL,
  `roomFeatureCopy4` varchar(50) NOT NULL,
  `roomFeatureIcon5` tinyint NOT NULL,
  `roomFeatureCopy5` varchar(50) NOT NULL,
  `roomFeatureIcon6` tinyint NOT NULL,
  `roomFeatureCopy6` varchar(50) NOT NULL,
  `roomFeatureIcon7` tinyint NOT NULL,
  `roomFeatureCopy7` varchar(50) NOT NULL,

  `roomTypeIcon0` tinyint NOT NULL,
  `roomTypeCopy0` varchar(50) NOT NULL,
  `roomTypeIcon1` tinyint NOT NULL,
  `roomTypeCopy1` varchar(50) NOT NULL,
  `roomTypeIcon2` tinyint NOT NULL,
  `roomTypeCopy2` varchar(50) NOT NULL,
  `roomTypeIcon3` tinyint NOT NULL,
  `roomTypeCopy3` varchar(50) NOT NULL,

  `hotelClass` float(2, 1) NOT NULL,
  `hotelStyle` text NOT NULL,

  `isSpecialOffered` tinyint NOT NULL,
  `special` varchar(50) NOT NULL
);

-- mysql -u root < database/schema.sql